spring:
  application:
    name: aop
  datasource:
    url: jdbc:postgresql://localhost:5432/perfomance_statistics
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: ru.suslov.perfomance_statistics.configuration.CustomPhysicalNamingStrategy
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

logging:
  logback:
    rollingpolicy:
      max-file-size: ${LOG_MAX_SIZE:30MB}
      max-history: ${LOG_MAX_FILE:10}

spring-doc:
  packages-to-scan: ru.suslov.perfomance_statistics.controller
  api-docs:
    enabled: true
  swagger-ui:
    path: documentation
    enabled: true
    operationsSorter: method
    tryItOutEnabled: true
    filter: true
    tagsSorter: alpha

http-logging:
  enabled: true